import bcrypt from "bcryptjs"

const data = {
    users:[
        {
            name : 'Jhon',
            email : 'admin@example.com',
            password:bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            name : 'Jane',
            email : 'user@example.com',
            password:bcrypt.hashSync('123456'),
            isAdmin: false,
        },
    ],
   products : [
    {
        name:'Silk Saree',
        slug: 'free-saree1',
        category: 'Sarees',
        image: '/images/saree_1.jpeg',
        price: 70,
        brand: 'kanchivaram',
        rating : 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular saree',
        isFeatured: true,
        banner: '/images/saree_1.jpeg',
    },
    {
        name:'Silk Saree',
        slug: 'free-saree2',
        category: 'Sarees',
        image: '/images/saree_2.jpeg',
        price: 70,
        brand: 'Siri',
        rating : 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular saree',
        isFeatured: true,
        banner: '/images/saree_1.jpeg',
    },
    {
        name:'Silk Sraee',
        slug: 'free-saree3',
        category: 'Sarees',
        image: '/images/saree_3.webp',
        price: 70,
        brand: 'Gui kranthi',
        rating : 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular saree',
        isFeatured: true,
        banner: '/images/saree_1.jpeg',
    },
    {
        name:'Silk Sraee',
        slug: 'free-saree4',
        category: 'Sarees',
        image: '/images/saree_4.jpg',
        price: 70,
        brand: 'Arshiyal',
        rating : 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular saree',
        isFeatured: true,
        banner: '/images/saree_1.jpeg',
    },
    {
        name:'Silk Sraee',
        slug: 'free-saree5',
        category: 'Sarees',
        image: '/images/saree_5.jpeg',
        price: 70,
        brand: 'Snihal',
        rating : 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular saree',
        isFeatured: true,
        banner: '/images/saree_1.jpeg',
    },
    {
        name:'Lehanga',
        slug: 'free-lehanga1',
        category: 'Lehangas',
        image: '/images/lehenga_1.webp',
        price: 170,
        brand: 'Stars',
        rating : 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular saree',
        isFeatured: true,
        banner: '/images/lehenga_1.webp',
    },
    {
        name:'Lehanga',
        slug: 'free-lehanga2',
        category: 'Lehangas',
        image: '/images/lehenga_2.webp',
        price: 170,
        brand: 'Malhotra',
        rating : 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular saree',
        isFeatured: true,
        banner: '/images/lehenga_2.webp',
    },
    {
        name:'Lehanga',
        slug: 'free-lehanga3',
        category: 'Lehangas',
        image: '/images/lehenga_3.jpeg',
        price: 170,
        brand: 'Shewan',
        rating : 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular lehanga',
        isFeatured: true,
        banner: '/images/lehenga_3.jpeg',
    },
    {
        name:'Lehanga',
        slug: 'free-lehanga4',
        category: 'Lehangas',
        image: '/images/lehenga_4.jpg',
        price: 170,
        brand: 'Adithi',
        rating : 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular lehanga',
        isFeatured: true,
        banner: '/images/lehenga_4.jpg',
    },
    ],
}
export default data